# Generated by Django 4.1.8 on 2023-10-28 15:17

from django.db import migrations, models
import django.db.models.deletion
import wfavicon.models
import wfavicon.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaviconSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_theme_color",
                    models.CharField(
                        blank=True,
                        help_text="Hex colour value",
                        max_length=7,
                        validators=[wfavicon.validators.validate_hex],
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="App name for manifest.json",
                        max_length=128,
                    ),
                ),
                (
                    "base_favicon_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favicon",
            },
            bases=(models.Model, wfavicon.models.FaviconRenditions),
        ),
    ]
