# Generated by Django 4.2.6 on 2023-10-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wfavicon", "0002_alter_faviconsettings_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faviconsettings",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
