# Generated by Django 4.2.6 on 2023-11-01 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_contactpage_search_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="search_image",
        ),
    ]
